name: Post Daily Standup (M-F)

on:
  schedule:
    - cron:  '0 4 * * 1-5' # Runs M-F at 4:00am UTC

jobs:
  create_discussions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MLH-Fellowship/create-standup-discussions@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ORGANIZATION_TOKEN }}
        with:
          organization: "MLH-Fellowship"
          team_slugs: "pod-2-0-0, pod-2-0-1, pod-2-0-2, pod-2-0-3, pod-2-1-0, pod-2-1-1, pod-2-1-2, pod-2-1-3, pod-2-2-0, pod-2-2-1"
