name: Post Daily Standup (M-F)

on:
  schedule:
    - cron:  '0 4 7 6 1-5' #'0 4 * * 1-5' # Runs M-F at 4:00am UTC

jobs:
  create_discussions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MLH-Fellowship/create-standup-discussions@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ORGANIZATION_TOKEN }}
        with:
          organization: "MLH-Fellowship"
          team_slugs: "pod-3-0-0, pod-3-0-1, pod-3-0-2, pod-3-3-0, pod-3-3-1, pod-3-3-2, pod-3-3-3, pod-3-3-4, pod-3-3-5, pod-3-3-6, pod-3-3-7"
